port = 5000
name = "My Motiv Library"
cache_path = "../.cache"
worker_threads = 2
webapp_path = "../frontend/build"

[[media]]
#TODO: fix some proper "default" which can be used to run tests in the CLooUuud
path = "/home/alexander/Cloud/Backgrounds"

#[[media]]
#TODO: fix some proper "default" which can be used to run tests in the CLooUuud
#path = "./test/video"

[database]
url = "postgres://postgres:mysecretpassword@localhost:5432/postgres"
