port = 5000
name = "My Motiv Library"
cache_path = "./cache"
worker_threads = 2
webapp_path = "../frontend/build"

[[media]]
path = "./dummy-data/originals/videos"

[[media]]
path = "./dummy-data/originals/pictures"

[database]
url = "postgres://postgres:mysecretpassword@localhost:5432/postgres"
