CREATE TABLE media (
  id SERIAL PRIMARY KEY,
  name VARCHAR NOT NULL,
  path VARCHAR UNIQUE NOT NULL,
  processed BOOLEAN NOT NULL DEFAULT 'f',
  processed_levels INTEGER NOT NULL DEFAULT 0,
  hash VARCHAR NOT NULL,
  modified INTEGER NOT NULL,
  timestamp INTEGER NOT NULL,
  media_type INTEGER NOT NULL DEFAULT 0
)
