version: "3.9"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: mysecretpassword
  server:
    links:
      - "db"
    image: "alekzanther/motiv:latest"
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: "postgres://postgres:mysecretpassword@db:5432/postgres"
